// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Open a WebSocket chat connection to the gateway and proxy all frames
 * through Tauri events (`zeroclaw://chat-frame`).
 */
async chatConnect(req: ChatConnectRequest) : Promise<Result<ChatSessionInfo, ChatError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("chat_connect", { req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Send a JSON frame to an open chat session.
 */
async chatSend(req: ChatSendRequest) : Promise<Result<null, ChatError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("chat_send", { req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Close a chat session.
 */
async chatDisconnect(req: ChatCloseRequest) : Promise<Result<null, ChatError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("chat_disconnect", { req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async chatCapabilities() : Promise<ChatCapabilities> {
    return await TAURI_INVOKE("chat_capabilities");
},
async prepareChatAttachments(req: PrepareChatAttachmentsRequest) : Promise<Result<ChatFileEntry[], ChatError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("prepare_chat_attachments", { req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listConnections() : Promise<Result<Connection[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_connections") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getActiveConnection() : Promise<Result<Connection | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_active_connection") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async upsertConnection(conn: Connection) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upsert_connection", { conn }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeConnection(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_connection", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setActiveConnection(id: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_active_connection", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Explicit "re-run activation for the current active connection" command.
 * Exposed so the UI can offer a retry button when activation fails.
 */
async reactivate() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reactivate") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Non-mutating connectivity probe for a saved connection.
 * 
 * This only checks the connection's current URL. It never starts a managed
 * gateway and never opens an SSH tunnel; activation remains the only path that
 * owns lifecycle side effects.
 */
async connectionProbe(id: string) : Promise<Result<ConnectionProbeResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("connection_probe", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async configGetSummaries() : Promise<Result<ConfigSummaries, ConfigSummaryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("config_get_summaries") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async discoverLocalGateway() : Promise<Result<DiscoveredLocal | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("discover_local_gateway") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async ensureToken(id: string) : Promise<Result<PairResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ensure_token", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pairWithCode(id: string, code: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pair_with_code", { id, code }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Execute an HTTP request via Rust `reqwest` and return the raw response.
 * 
 * Reuses the app-wide `reqwest::Client` from managed state so connection
 * pools and TLS sessions persist across calls instead of being rebuilt on
 * every IPC round trip.
 */
async gatewayRequest(req: GatewayHttpRequest) : Promise<Result<GatewayHttpResponse, GatewayHttpError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("gateway_request", { req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async detectLocalBinary() : Promise<Result<DetectedBinary | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("detect_local_binary") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async installInstructions() : Promise<InstallInstructions> {
    return await TAURI_INVOKE("install_instructions");
},
async runtimeStart(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("runtime_start", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async runtimeStop() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("runtime_stop") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async runtimeStatus() : Promise<Result<SupervisorStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("runtime_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setupGetStatus(context: SetupContext) : Promise<Result<SetupStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("setup_get_status", { context }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setupRunAction(req: SetupActionRequest) : Promise<Result<SetupActionResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("setup_run_action", { req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sshOpenTunnel(id: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ssh_open_tunnel", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sshCloseTunnel(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ssh_close_tunnel", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async agentWorkspaceListAgents() : Promise<Result<AgentWorkspaceAgent[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_workspace_list_agents") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async agentWorkspaceListDir(alias: string, path: string | null) : Promise<Result<AgentWorkspaceEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_workspace_list_dir", { alias, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async agentWorkspaceReadFile(alias: string, path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_workspace_read_file", { alias, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async agentWorkspaceWriteFile(alias: string, path: string, content: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_workspace_write_file", { alias, path, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async agentWorkspaceCreateFile(alias: string, path: string, content: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_workspace_create_file", { alias, path, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async agentWorkspaceCreateDir(alias: string, path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_workspace_create_dir", { alias, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async agentWorkspaceDelete(alias: string, path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_workspace_delete", { alias, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async workspaceOpenRoot(path: string) : Promise<Result<WorkspaceLocalState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_open_root", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async workspaceGetState() : Promise<Result<WorkspaceLocalState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_get_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async workspaceImportLegacyState(currentRoot: string | null, recentRoots: string[]) : Promise<Result<WorkspaceLocalState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_import_legacy_state", { currentRoot, recentRoots }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async workspaceGetRoot() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_get_root") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async workspaceListDir(path: string) : Promise<Result<DirEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_list_dir", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async workspaceReadFile(path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_read_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async workspaceWriteFile(path: string, content: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_write_file", { path, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async workspaceWatchStart(path: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_watch_start", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async workspaceWatchStop() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_watch_stop") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async workspaceGitStatus(root: string) : Promise<Result<WorkspaceGitStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_git_status", { root }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async chatLocalGetSelectedSession(workspaceRoot: string | null, mode: string, agentAlias: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("chat_local_get_selected_session", { workspaceRoot, mode, agentAlias }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async chatLocalSetSelectedSession(workspaceRoot: string | null, mode: string, agentAlias: string, sessionId: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("chat_local_set_selected_session", { workspaceRoot, mode, agentAlias, sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async chatLocalListSessionWorkspaces() : Promise<Result<SessionWorkspaceBinding[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("chat_local_list_session_workspaces") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async chatLocalAssignSessionWorkspace(sessionId: string, workspaceRoot: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("chat_local_assign_session_workspace", { sessionId, workspaceRoot }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async chatLocalGetTranscript(workspaceRoot: string | null, mode: string, agentAlias: string, sessionId: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("chat_local_get_transcript", { workspaceRoot, mode, agentAlias, sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async chatLocalSetTranscript(workspaceRoot: string | null, mode: string, agentAlias: string, sessionId: string, transcriptJson: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("chat_local_set_transcript", { workspaceRoot, mode, agentAlias, sessionId, transcriptJson }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async chatLocalClearTranscript(workspaceRoot: string | null, mode: string, agentAlias: string, sessionId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("chat_local_clear_transcript", { workspaceRoot, mode, agentAlias, sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AgentSummary = { alias: string; label: string; picker_badge: string | null; enabled: boolean; dispatchable: boolean; missing: string[]; model_provider: string; risk_profile: string; runtime_profile: string; channels: string[]; skill_bundles: string[]; knowledge_bundles: string[]; mcp_bundles: string[]; cron_jobs: string[]; peer_groups: string[] }
export type AgentWorkspaceAgent = { alias: string; workspace_path: string; workspace_exists: boolean; file_count: number }
export type AgentWorkspaceEntry = { name: string; path: string; isDir: boolean; size: number | null }
export type AuthConfig = { mode: AuthMode; 
/**
 * Stored bearer token. Persisted alongside the connection (Phase 2 will
 * move this to OS keychain).
 */
token: string | null }
export type AuthMode = 
/**
 * Use the gateway's pairing flow to mint a fresh token.
 */
"pairing" | 
/**
 * User supplied a token directly.
 */
"token"
export type ChatCapabilities = { max_attachment_bytes: number; max_attachment_request_bytes: number }
export type ChatCloseRequest = { session_id: string }
export type ChatConnectRequest = { url: string; agent_alias: string; session_id: string | null; token: string; mode: ChatMode | null; workspace_dir: string | null; model_provider: string | null; model: string | null }
export type ChatError = { message: string }
export type ChatFileEntry = { path: string | null; data_b64: string | null; filename: string; mime_type: string; size: number; source: string }
export type ChatMode = "chat" | "acp"
export type ChatSendRequest = { session_id: string; frame: string }
export type ChatSessionInfo = { session_id: string }
export type ConfigSummaries = { agents: AgentSummary[]; risk_profiles: RiskProfileSummary[]; runtime_profiles: RuntimeProfileSummary[] }
export type ConfigSummaryError = { message: string }
export type Connection = { id: string; name: string; transport: Transport; 
/**
 * Gateway base URL as seen FROM the workspace. For SSH connections this
 * is `http://127.0.0.1:<local_forward_port>` (set after tunnel comes up).
 */
url: string; ssh: SshConfig | null; auth: AuthConfig; lifecycle: Lifecycle; runtime_source?: RuntimeSource; 
/**
 * For `Lifecycle::Managed` connections only.
 */
binary_path: string | null }
export type ConnectionProbeResult = { connection_id: string; reachable: boolean; latency_ms: number | null; status: string; error: string | null; checked_at: string }
export type DetectedBinary = { path: string; version: string | null }
export type DirEntry = { name: string; path: string; isDir: boolean; size: number | null }
export type DiscoveredLocal = { url: string; healthy: boolean; require_pairing: boolean }
export type GatewayHttpError = { message: string }
export type GatewayHttpRequest = { method: string; url: string; headers: ([string, string])[]; body: string | null }
export type GatewayHttpResponse = { status: number; headers: ([string, string])[]; body: string }
export type InstallInstructions = { 
/**
 * The one-liner the user copy-pastes into their terminal.
 */
command: string; 
/**
 * Pretty notes the UI can render under the command.
 */
notes: string[]; 
/**
 * Where to point the user if they want to read more first.
 */
docs_url: string }
export type Lifecycle = 
/**
 * We spawn `zeroclaw` ourselves and own its lifetime.
 */
"managed" | 
/**
 * Gateway is already running — we never spawn, never kill.
 */
"attach" | 
/**
 * Gateway lives on a different host; lifecycle is owned remotely.
 */
"remote"
export type PairResult = { outcome: string; token: string | null }
export type PrepareChatAttachmentsRequest = { paths: string[]; connection_id: string }
export type RiskProfileSummary = { alias: string; label: string; picker_badge: string | null; used_by_agents: string[]; level: string; workspace_only: boolean | null; allowed_commands: string[]; forbidden_paths: string[]; allowed_roots: string[]; require_approval_for_medium_risk: boolean | null; block_high_risk_commands: boolean | null; auto_approve: string[]; always_ask: string[]; allowed_tools: string[]; excluded_tools: string[]; sandbox_enabled: boolean | null; sandbox_backend: string }
export type RuntimeProfileSummary = { alias: string; label: string; picker_badge: string | null; used_by_agents: string[]; agentic: boolean | null; max_tool_iterations: number | null; max_actions_per_hour: number | null; max_cost_per_day_cents: number | null; shell_timeout_secs: number | null; max_context_tokens: number | null; max_history_messages: number | null; compact_context: boolean | null; parallel_tools: boolean | null; strict_tool_parsing: boolean | null; tool_dispatcher: string }
export type RuntimeSource = 
/**
 * App-private runtime shipped as a bundled Tauri sidecar.
 */
"bundled_inner" | 
/**
 * A user-installed or user-selected zeroclaw binary.
 */
"external_path" | 
/**
 * A gateway owned outside this desktop app.
 */
"attached"
export type SessionWorkspaceBinding = { session_id: string; workspace_root: string }
export type SetupAction = { id: SetupActionId; label: string; description: string; command: string[]; requires_confirmation: boolean }
export type SetupActionId = "browser_install_agent_browser" | "browser_install_chrome_for_testing" | "docker_pull_alpine"
export type SetupActionRequest = { action_id: SetupActionId; context: SetupContext }
export type SetupActionResult = { success: boolean; exit_code: number | null; stdout: string; stderr: string }
export type SetupCapabilityId = "browser_agent_browser" | "python_skills" | "docker_runtime" | "sandbox_backend" | "mcp_stdio"
export type SetupCheck = { id: string; label: string; status: SetupCheckStatus; detail: string }
export type SetupCheckStatus = "pass" | "warn" | "fail" | "info"
export type SetupConfigRecommendation = { id: string; label: string; description: string; path: string; value: SetupConfigValue; merge: string | null }
export type SetupConfigValue = { type: "bool"; value: boolean } | { type: "string"; value: string } | { type: "string_array"; value: string[] }
export type SetupContext = { capability_id: SetupCapabilityId; config_prefix: string; alias: string | null; mcp_transport: string | null; mcp_command: string | null }
export type SetupOverallStatus = "ready" | "needs_action" | "manual" | "unavailable"
export type SetupRemediation = { title: string; body: string; commands: string[][] }
export type SetupStatus = { capability_id: SetupCapabilityId; title: string; summary: string; overall: SetupOverallStatus; checks: SetupCheck[]; actions: SetupAction[]; remediations: SetupRemediation[]; config_recommendations: SetupConfigRecommendation[] }
export type SshConfig = { host: string; user: string; port: number | null; 
/**
 * Path to the SSH private key. `None` falls back to ssh-agent / default ids.
 */
key_path: string | null; 
/**
 * Gateway port on the REMOTE host (default 42617).
 */
remote_port: number; 
/**
 * Local port the workspace forwards to. `None` → pick an ephemeral port.
 */
local_forward_port: number | null }
export type SupervisorStatus = "Stopped" | "Running" | "Exited" | "Backoff" | "Error"
export type Transport = 
/**
 * Direct loopback (`http://127.0.0.1:PORT`).
 */
"local" | 
/**
 * Direct HTTP(S) to a hostname.
 */
"http" | 
/**
 * SSH-tunneled (workspace runs `ssh -L ...` and points local to the tunnel).
 */
"ssh" | 
/**
 * Tailscale-routed (semantically `Http` over MagicDNS; kept separate for UI).
 */
"tailscale"
export type WorkspaceGitStatus = { root: string; is_repo: boolean; branch: string | null; changed_count: number; diff_stat: string | null }
export type WorkspaceLocalState = { current_root: string | null; recent_roots: string[] }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
