// Typed Tauri command invokers + event payload types.
//
// Command signatures and their request/response types are generated by
// tauri-specta into `./bindings.ts` (from the `#[specta::specta]` Rust
// commands in `src-tauri/src/commands/`). They are regenerated on every
// `pnpm tauri dev` (and via `cargo test export_bindings`), so this file no
// longer mirrors Rust by hand.
//
// tauri-specta renders Rust `Result<T, E>` as a discriminated union
// `{ status: "ok"; data: T } | { status: "error"; error: E }` that never
// throws. The rest of this app predates that and expects commands to reject
// on error, so `unwrap()` converts the union back to throw-on-error and the
// re-exported wrappers keep their original (`Promise<T>`) shape.

import { commands } from "./bindings";
import type { Result } from "./bindings";
import type {
  ChatCloseRequest,
  ChatConnectRequest,
  ChatSendRequest,
  Connection,
  GatewayHttpRequest,
} from "./bindings";

/** Unpack a specta `Result` union into a throwing promise (Tauri's native IPC
 * semantics), so existing `try/catch` call sites keep working unchanged. */
async function unwrap<T, E>(result: Promise<Result<T, E>>): Promise<T> {
  const r = await result;
  if (r.status === "ok") return r.data;
  throw r.error;
}

// ---- Types (generated, see ./bindings.ts) ----

export type {
  AuthConfig,
  AuthMode,
  ChatCloseRequest,
  ChatConnectRequest,
  ChatError,
  ChatSendRequest,
  ChatSessionInfo,
  Connection,
  DetectedBinary,
  DirEntry,
  DiscoveredLocal,
  GatewayHttpError,
  GatewayHttpRequest,
  GatewayHttpResponse,
  InstallInstructions,
  Lifecycle,
  PairResult,
  SshConfig,
  SupervisorStatus,
  Transport,
} from "./bindings";

// ---- Event payloads emitted by the backend (not specta-typed) ----

export interface HealthEvent {
  connection_id: string | null;
  url: string | null;
  healthy: boolean;
}

/**
 * Activation lifecycle events emitted on `zeroclaw://activation` while the
 * backend brings a connection online (probe → spawn → wait healthy → pair).
 * Tagged via serde's `type` field.
 */
export type ActivationStep =
  | { type: "started"; connection_id: string }
  | { type: "probing" }
  | { type: "starting_gateway"; binary_path: string }
  | { type: "awaiting_healthy" }
  | { type: "pairing" }
  | { type: "ready" }
  | { type: "binary_missing" }
  | { type: "needs_manual_pairing" }
  | { type: "failed"; message: string };

export interface FileEvent {
  path: string;
  kind: "created" | "modified" | "removed" | "other";
}

// ---- Connection commands ----

export const listConnections = () => unwrap(commands.listConnections());

export const getActiveConnection = () => unwrap(commands.getActiveConnection());

export const upsertConnection = (conn: Connection) =>
  unwrap(commands.upsertConnection(conn));

export const removeConnection = (id: string) =>
  unwrap(commands.removeConnection(id));

export const setActiveConnection = (id: string | null) =>
  unwrap(commands.setActiveConnection(id));

export const reactivate = () => unwrap(commands.reactivate());

// ---- Gateway commands ----

export const discoverLocalGateway = () =>
  unwrap(commands.discoverLocalGateway());

export const ensureToken = (id: string) => unwrap(commands.ensureToken(id));

export const pairWithCode = (id: string, code: string) =>
  unwrap(commands.pairWithCode(id, code));

// ---- Chat commands ----

export const chatConnect = (req: ChatConnectRequest) =>
  unwrap(commands.chatConnect(req));

export const chatSend = (req: ChatSendRequest) => unwrap(commands.chatSend(req));

export const chatDisconnect = (req: ChatCloseRequest) =>
  unwrap(commands.chatDisconnect(req));

// ---- Runtime commands ----

export const detectLocalBinary = () => unwrap(commands.detectLocalBinary());

export const installInstructions = commands.installInstructions;

export const runtimeStart = (id: string) => unwrap(commands.runtimeStart(id));

export const runtimeStop = () => unwrap(commands.runtimeStop());

export const runtimeStatus = () => unwrap(commands.runtimeStatus());

// ---- SSH commands ----

export const sshOpenTunnel = (id: string) => unwrap(commands.sshOpenTunnel(id));

export const sshCloseTunnel = (id: string) =>
  unwrap(commands.sshCloseTunnel(id));

// ---- Gateway HTTP client commands ----

export const gatewayRequest = (req: GatewayHttpRequest) =>
  unwrap(commands.gatewayRequest(req));

// ---- Workspace FS commands ----

export const workspaceOpenRoot = (path: string) =>
  unwrap(commands.workspaceOpenRoot(path));

export const workspaceGetRoot = () => unwrap(commands.workspaceGetRoot());

export const workspaceListDir = (path: string) =>
  unwrap(commands.workspaceListDir(path));

export const workspaceReadFile = (path: string) =>
  unwrap(commands.workspaceReadFile(path));

export const workspaceWriteFile = (path: string, content: string) =>
  unwrap(commands.workspaceWriteFile(path, content));

export const workspaceWatchStart = (path: string | null = null) =>
  unwrap(commands.workspaceWatchStart(path));

export const workspaceWatchStop = () => unwrap(commands.workspaceWatchStop());
